// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBouNB3mKHrxntBB4-xkK6-bbnMef-eeUA',
    appId: '1:427017630970:web:35de98e8f58e071c9d4543',
    messagingSenderId: '427017630970',
    projectId: 'isht-2627b',
    authDomain: 'isht-2627b.firebaseapp.com',
    databaseURL: 'https://isht-2627b-default-rtdb.firebaseio.com',
    storageBucket: 'isht-2627b.appspot.com',
    measurementId: 'G-YTJ47R3YZP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCoBfMt6vOTFSH-DQBW2pa2QVeRSmD-ZIc',
    appId: '1:427017630970:android:c9ca4656b23afd5f9d4543',
    messagingSenderId: '427017630970',
    projectId: 'isht-2627b',
    databaseURL: 'https://isht-2627b-default-rtdb.firebaseio.com',
    storageBucket: 'isht-2627b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBlDKfW18MSLspp-SnwXUZn0WjCkT3JydA',
    appId: '1:427017630970:ios:a7b7fb9ec2e3e39a9d4543',
    messagingSenderId: '427017630970',
    projectId: 'isht-2627b',
    databaseURL: 'https://isht-2627b-default-rtdb.firebaseio.com',
    storageBucket: 'isht-2627b.appspot.com',
    iosClientId: '427017630970-ql4hdajn5d661ui8in990invseu79tbq.apps.googleusercontent.com',
    iosBundleId: 'com.example.isht',
  );
}
